1.1-1.3
js-tasks-ru/js-20220111_skubiduev pull request #3
Opened 2022-01-15 05:37 UTC by Skubiduev

Все задания 1 модуля.

2022-01-15 05:38 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-16 18:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-01-17 16:41 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === 'asc' ? copyOfArr : copyOfArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-01-17 16:41 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
>  export const pick = (obj, ...fields) => {
👍 good

2022-01-17 16:41 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  for (const key of Object.keys(obj)) {
👍 good

2022-01-17 16:41 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2022-01-17 20:03 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-18 14:36 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
>  export function sortStrings(arr, param = 'asc') {
👍 good

2022-01-18 14:36 UTC, dosandk approved these changes
👍 good

2022-01-18 14:36 UTC, merged